export interface LexisItem {
  id: string;
  word: string;
  partOfSpeech: 'noun' | 'verb' | 'adjective' | 'adverb' | 'idiom';
  definition: string;
  example: string;
  ipa: string;
  synonyms: string[];
  category: 'Academic' | 'Business' | 'Travel' | 'Conversational' | 'Descriptive' | 'Idioms' | 'Custom';
  tags?: string[];
  level: 'B1' | 'B2' | 'C1' | 'C2';
  starred?: boolean;
  dateAdded?: string;
}

export interface LexisPack {
  id: string;
  title: string;
  description: string;
  color: string;
  badgeBg: string;
  words: LexisItem[];
}

export const LEXIS_PACKS: LexisPack[] = [
  {
    id: 'academic',
    title: 'Academic & IELTS Master',
    description: 'High-yield C1/C2 terms essential for essays, scholarly analysis, and formal debate.',
    color: 'text-indigo-400 border-indigo-500/70 bg-indigo-950/30',
    badgeBg: 'bg-indigo-950/70 text-indigo-300 border-indigo-800',
    words: [
      {
        id: 'acad_1',
        word: 'Ephemeral',
        partOfSpeech: 'adjective',
        definition: 'Lasting for a very short, transitory duration.',
        example: 'The ephemeral nature of social media trends means virality fades within hours.',
        ipa: '/ɪˈfem.ər.əl/',
        synonyms: ['transient', 'fleeting', 'momentary', 'evanescent'],
        category: 'Academic',
        tags: ['Academic', 'Scholarly', 'Essay', 'Philosophy'],
        level: 'C1',
        starred: true,
      },
      {
        id: 'acad_2',
        word: 'Ubiquitous',
        partOfSpeech: 'adjective',
        definition: 'Present, appearing, or encountered everywhere at once.',
        example: 'Digital algorithms have become ubiquitous in modern decision-making.',
        ipa: '/juːˈbɪk.wɪ.təs/',
        synonyms: ['omnipresent', 'pervasive', 'universal', 'widespread'],
        category: 'Academic',
        tags: ['Academic', 'Technology', 'Formal', 'Research'],
        level: 'C1',
      },
      {
        id: 'acad_3',
        word: 'Juxtapose',
        partOfSpeech: 'verb',
        definition: 'To place contrasting things side by side for comparison.',
        example: 'The essay juxtaposes traditional pedagogical values with experimental digital learning.',
        ipa: '/ˌdʒʌk.stəˈpoʊz/',
        synonyms: ['contrast', 'collocate', 'compare', 'set side by side'],
        category: 'Academic',
        tags: ['Academic', 'Analysis', 'Writing'],
        level: 'C2',
      },
      {
        id: 'acad_4',
        word: 'Paradigm',
        partOfSpeech: 'noun',
        definition: 'A standard model, system, or typical example of something.',
        example: 'Artificial intelligence represents a fundamental paradigm shift in knowledge work.',
        ipa: '/ˈpær.ə.daɪm/',
        synonyms: ['archetype', 'prototype', 'benchmark', 'framework'],
        category: 'Academic',
        tags: ['Academic', 'Science', 'Business', 'Framework'],
        level: 'C1',
      },
      {
        id: 'acad_5',
        word: 'Eloquent',
        partOfSpeech: 'adjective',
        definition: 'Fluent, persuasive, and articulately expressive in speech or writing.',
        example: 'Her eloquent defense of ethical technology captivated the entire auditorium.',
        ipa: '/ˈel.ə.kwənt/',
        synonyms: ['articulate', 'persuasive', 'fluent', 'poignant'],
        category: 'Academic',
        tags: ['Academic', 'Public Speaking', 'Rhetoric'],
        level: 'C1',
        starred: true,
      },
      {
        id: 'acad_6',
        word: 'Pernicious',
        partOfSpeech: 'adjective',
        definition: 'Having a harmful effect, especially in a gradual or subtle way.',
        example: 'Misinformation has a pernicious influence on public civic trust.',
        ipa: '/pərˈnɪʃ.əs/',
        synonyms: ['insidious', 'detrimental', 'destructive', 'damaging'],
        category: 'Academic',
        tags: ['Academic', 'Critical Thinking', 'Social Studies'],
        level: 'C2',
      },
      {
        id: 'acad_7',
        word: 'Surreptitiously',
        partOfSpeech: 'adverb',
        definition: 'Done in a secretive, stealthy, or unobserved manner.',
        example: 'He surreptitiously glanced at his watch during the lengthy lecture.',
        ipa: '/ˌsɜː.rəpˈtɪʃ.əs.li/',
        synonyms: ['covertly', 'stealthily', 'furtively', 'secretly'],
        category: 'Academic',
        tags: ['Academic', 'Literature', 'Behavior'],
        level: 'C2',
      },
    ],
  },
  {
    id: 'business',
    title: 'Executive & Business Lexis',
    description: 'Strategic language for corporate negotiations, presentations, and team leadership.',
    color: 'text-emerald-400 border-emerald-500/70 bg-emerald-950/30',
    badgeBg: 'bg-emerald-950/70 text-emerald-300 border-emerald-800',
    words: [
      {
        id: 'biz_1',
        word: 'Leverage',
        partOfSpeech: 'verb',
        definition: 'To utilize an existing asset, skill, or relationship to its maximum advantage.',
        example: 'We must leverage our customer insights to optimize the new product roadmap.',
        ipa: '/ˈlev.ɚ.ɪdʒ/',
        synonyms: ['capitalize on', 'exploit', 'utilize', 'harness'],
        category: 'Business',
        tags: ['Business', 'Strategy', 'Finance', 'Leadership'],
        level: 'B2',
      },
      {
        id: 'biz_2',
        word: 'Mitigate',
        partOfSpeech: 'verb',
        definition: 'To make something bad or dangerous less severe, serious, or painful.',
        example: 'Proactive compliance audits mitigate financial and legal risks.',
        ipa: '/ˈmɪt̬.ə.ɡeɪt/',
        synonyms: ['alleviate', 'diminish', 'attenuate', 'cushion'],
        category: 'Business',
        tags: ['Business', 'Risk Management', 'Corporate'],
        level: 'C1',
        starred: true,
      },
      {
        id: 'biz_3',
        word: 'Synergy',
        partOfSpeech: 'noun',
        definition: 'The combined interaction of two elements producing a greater sum than individual parts.',
        example: 'The merger created strong synergy across global distribution channels.',
        ipa: '/ˈsɪn.ɚ.dʒi/',
        synonyms: ['collaboration', 'cohesion', 'symbiosis', 'teamwork'],
        category: 'Business',
        tags: ['Business', 'Teamwork', 'Management'],
        level: 'B2',
      },
      {
        id: 'biz_4',
        word: 'Benchmark',
        partOfSpeech: 'noun',
        definition: 'A standard or point of reference against which things may be compared or assessed.',
        example: 'Our quarterly retention rate serves as an industry benchmark for SaaS platforms.',
        ipa: '/ˈbentʃ.mɑːrk/',
        synonyms: ['standard', 'criterion', 'touchstone', 'gauge'],
        category: 'Business',
        tags: ['Business', 'Analytics', 'Metrics'],
        level: 'B2',
      },
      {
        id: 'biz_5',
        word: 'Pivot',
        partOfSpeech: 'verb',
        definition: 'To rapidly shift strategic business direction or target market orientation.',
        example: 'When market conditions shifted, the enterprise decided to pivot toward cloud security.',
        ipa: '/ˈpɪv.ət/',
        synonyms: ['reorient', 'shift', 'adapt', 'transition'],
        category: 'Business',
        tags: ['Business', 'Startup', 'Innovation', 'Agile'],
        level: 'B2',
      },
      {
        id: 'biz_6',
        word: 'Seamlessly',
        partOfSpeech: 'adverb',
        definition: 'Smoothly and continuously, without noticeable transitions or interruptions.',
        example: 'The payment gateway integrates seamlessly with the existing mobile app checkout.',
        ipa: '/ˈsiːm.ləs.li/',
        synonyms: ['flawlessly', 'smoothly', 'effortlessly', 'harmoniously'],
        category: 'Business',
        tags: ['Business', 'Technology', 'Product'],
        level: 'B2',
      },
    ],
  },
  {
    id: 'travel',
    title: 'Travel & Global Journeys',
    description: 'Sophisticated terminology for world travel, hospitality, itineraries, and cultural exploration.',
    color: 'text-amber-400 border-amber-500/70 bg-amber-950/30',
    badgeBg: 'bg-amber-950/70 text-amber-300 border-amber-800',
    words: [
      {
        id: 'trv_1',
        word: 'Wanderlust',
        partOfSpeech: 'noun',
        definition: 'A strong, innate, and persistent desire or impulse to travel the world.',
        example: 'Her intense wanderlust drove her to explore remote mountain villages across South America.',
        ipa: '/ˈwɑːn.dɚ.lʌst/',
        synonyms: ['itch to travel', 'passion for travel', 'adventurousness'],
        category: 'Travel',
        tags: ['Travel', 'Exploration', 'Adventure', 'Lifestyle'],
        level: 'B2',
        starred: true,
      },
      {
        id: 'trv_2',
        word: 'Picturesque',
        partOfSpeech: 'adjective',
        definition: 'Visually attractive, charming, or quaint, resembling a scenic painting.',
        example: 'We stayed in a picturesque coastal town with cobbled streets and pastel-colored cottages.',
        ipa: '/ˌpɪk.tʃərˈesk/',
        synonyms: ['scenic', 'charming', 'quaint', 'idyllic'],
        category: 'Travel',
        tags: ['Travel', 'Sightseeing', 'Descriptive'],
        level: 'B2',
      },
      {
        id: 'trv_3',
        word: 'Sojourn',
        partOfSpeech: 'noun',
        definition: 'A temporary stay or brief residence in a place away from home.',
        example: 'During his six-month sojourn in Kyoto, he immersed himself in traditional tea ceremonies.',
        ipa: '/ˈsoʊ.dʒɝːn/',
        synonyms: ['temporary stay', 'visit', 'stopover', 'retreat'],
        category: 'Travel',
        tags: ['Travel', 'Culture', 'Hospitality'],
        level: 'C1',
      },
      {
        id: 'trv_4',
        word: 'Itinerary',
        partOfSpeech: 'noun',
        definition: 'A planned route, schedule, or timetable of a journey.',
        example: 'Our travel itinerary includes guided historical tours in Rome and a culinary workshop in Florence.',
        ipa: '/aɪˈtɪn.ə.rer.i/',
        synonyms: ['route plan', 'schedule', 'timetable', 'travel plan'],
        category: 'Travel',
        tags: ['Travel', 'Planning', 'Logistics'],
        level: 'B1',
      },
      {
        id: 'trv_5',
        word: 'Cosmopolitan',
        partOfSpeech: 'adjective',
        definition: 'Familiar with and at ease in many different countries and international cultures.',
        example: 'London is a vibrant cosmopolitan metropolis home to communities from across the globe.',
        ipa: '/ˌkɑːz.məˈpɑː.lɪ.tən/',
        synonyms: ['international', 'multicultural', 'worldly', 'sophisticated'],
        category: 'Travel',
        tags: ['Travel', 'Culture', 'Urban', 'Academic'],
        level: 'C1',
      },
    ],
  },
  {
    id: 'conversational',
    title: 'Everyday Fluency & Idioms',
    description: 'Natural phrases and idiomatic vocabulary used daily by native English speakers.',
    color: 'text-sky-400 border-sky-500/70 bg-sky-950/30',
    badgeBg: 'bg-sky-950/70 text-sky-300 border-sky-800',
    words: [
      {
        id: 'conv_1',
        word: 'Serendipity',
        partOfSpeech: 'noun',
        definition: 'The happy occurrence of finding agreeable things not sought for.',
        example: 'We discovered the quiet seaside bookstore by pure serendipity on our vacation.',
        ipa: '/ˌser.ənˈdɪp.ə.t̬i/',
        synonyms: ['fortune', 'happy coincidence', 'fluke', 'good luck'],
        category: 'Conversational',
        tags: ['Conversational', 'Travel', 'Daily Fluency'],
        level: 'B2',
        starred: true,
      },
      {
        id: 'conv_2',
        word: 'Bite the bullet',
        partOfSpeech: 'idiom',
        definition: 'To force oneself to do something difficult or unpleasant without postponing.',
        example: 'I was dreading the dental visit, but I had to bite the bullet and get it done.',
        ipa: '/baɪt ðə ˈbʊl.ɪt/',
        synonyms: ['face the music', 'take the plunge', 'brace oneself'],
        category: 'Idioms',
        tags: ['Idioms', 'Conversational', 'Mindset'],
        level: 'B2',
      },
      {
        id: 'conv_3',
        word: 'Catch-22',
        partOfSpeech: 'noun',
        definition: 'A dilemma or difficult circumstance from which there is no escape because of mutually conflicting conditions.',
        example: 'You need job experience to get hired, but you need a job to get experience—a classic Catch-22.',
        ipa: '/ˌkætʃ.twen.tiˈtuː/',
        synonyms: ['no-win situation', 'paradox', 'quagmire'],
        category: 'Conversational',
        tags: ['Conversational', 'Business', 'Logic'],
        level: 'C1',
      },
      {
        id: 'conv_4',
        word: 'Call it a day',
        partOfSpeech: 'idiom',
        definition: 'To stop working on something, especially after finishing a substantial portion.',
        example: "We've made great progress on the draft; let's call it a day and resume tomorrow.",
        ipa: '/kɔːl ɪt ə deɪ/',
        synonyms: ['wrap up', 'clock out', 'conclude'],
        category: 'Idioms',
        tags: ['Idioms', 'Work', 'Daily Fluency'],
        level: 'B1',
      },
      {
        id: 'conv_5',
        word: 'Off the cuff',
        partOfSpeech: 'idiom',
        definition: 'Spoken or done spontaneously without prior planning or preparation.',
        example: 'He gave an inspiring speech completely off the cuff without any written notes.',
        ipa: '/ˌɔːf ðə ˈkʌf/',
        synonyms: ['extemporaneous', 'spontaneous', 'unrehearsed', 'impromptu'],
        category: 'Idioms',
        tags: ['Idioms', 'Public Speaking', 'Conversational'],
        level: 'B2',
      },
    ],
  },
  {
    id: 'descriptive',
    title: 'Descriptive & Sensory Nuance',
    description: 'Evocative adjectives and verbs to describe emotions, scenes, and textures with precision.',
    color: 'text-rose-400 border-rose-500/70 bg-rose-950/30',
    badgeBg: 'bg-rose-950/70 text-rose-300 border-rose-800',
    words: [
      {
        id: 'desc_1',
        word: 'Resplendent',
        partOfSpeech: 'adjective',
        definition: 'Attractive and impressive through being richly colorful or shining brightly.',
        example: 'The royal ballroom was resplendent in gold crystal chandeliers and vibrant velvet drapery.',
        ipa: '/rɪˈsplen.dənt/',
        synonyms: ['dazzling', 'splendid', 'magnificent', 'radiant'],
        category: 'Descriptive',
        tags: ['Descriptive', 'Visual', 'Sensory', 'Artistic'],
        level: 'C2',
      },
      {
        id: 'desc_2',
        word: 'Petrichor',
        partOfSpeech: 'noun',
        definition: 'A pleasant, distinctive earthy scent that frequently accompanies the first rain after warm weather.',
        example: 'The sweet petrichor of the morning shower refreshed the entire cedar grove.',
        ipa: '/ˈpet.rɪ.kɔːr/',
        synonyms: ['earthy aroma', 'rain scent'],
        category: 'Descriptive',
        tags: ['Descriptive', 'Sensory', 'Nature'],
        level: 'C2',
      },
      {
        id: 'desc_3',
        word: 'Melancholic',
        partOfSpeech: 'adjective',
        definition: 'Feeling or expressing a pensive, deep, or gentle sadness.',
        example: 'The cellist played a melancholic melody that echoed softly through the chapel.',
        ipa: '/ˌmel.əŋˈkɑː.lɪk/',
        synonyms: ['wistful', 'somber', 'pensive', 'sorrowful'],
        category: 'Descriptive',
        tags: ['Descriptive', 'Emotion', 'Music', 'Literature'],
        level: 'C1',
      },
      {
        id: 'desc_4',
        word: 'Cacophony',
        partOfSpeech: 'noun',
        definition: 'A harsh, discordant, noisy mixture of sounds.',
        example: 'The cacophony of sirens, car horns, and construction filled the busy city boulevard.',
        ipa: '/kəˈkɑː.fə.ni/',
        synonyms: ['din', 'clamor', 'racket', 'dissonance'],
        category: 'Descriptive',
        tags: ['Descriptive', 'Sound', 'City Life'],
        level: 'C1',
      },
      {
        id: 'desc_5',
        word: 'Luminous',
        partOfSpeech: 'adjective',
        definition: 'Full of or shedding light; brightly illuminated or vivid in clarity.',
        example: 'The full moon cast a luminous silver reflection across the calm ocean waters.',
        ipa: '/ˈluː.mə.nəs/',
        synonyms: ['radiant', 'shining', 'glowing', 'incandescent'],
        category: 'Descriptive',
        tags: ['Descriptive', 'Visual', 'Nature'],
        level: 'B2',
      },
    ],
  },
];

export const ALL_INITIAL_WORDS: LexisItem[] = LEXIS_PACKS.flatMap((pack) => pack.words);
